env: local

demo:
  jdbc:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.136.45.166:3306/demo?useUnicode=true;characterEncoding=UTF-8;zeroDateTimeBehavior=convertToNull;allowMultiQueries=true;&serverTimezone=Asia/Shanghai
    max_connections: 100
    name: wang
    password: debian990129
  redis:
    host: 127.0.0.1
    port: 6379
    pwd: 123456
    index: 0
    maxTotal: 100
    maxIdle: 100